# Generated by Django 5.1.4 on 2025-01-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.category'),
        ),
    ]
