# Generated by Django 5.1.4 on 2025-01-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='visivel',
            field=models.BooleanField(default=True, verbose_name='Visível na tela de vendas'),
        ),
    ]
