# Generated by Django 5.1.4 on 2025-01-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_itempedido_id_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do pedido'),
        ),
    ]
