# Generated by Django 5.1.4 on 2025-01-15 14:21

from django.db import migrations, models
from django.utils import timezone



class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_itempedido_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),  # Adicione default=timezone.now
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Criado', 'Criado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente'), ('Enviado', 'Enviado'), ('Finalizado', 'Finalizado')], default='Criado', max_length=10),
        ),
    ]
