# Generated by Django 5.1.4 on 2025-01-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_data_pedido_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
